# Generated by Django 5.0.6 on 2024-07-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medilabapp', '0003_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='DOB',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='phone',
            field=models.CharField(max_length=150),
        ),
    ]
